// Gary
// Copyright 2017 Keiran King

// LICENSE --------------------------------------------------------------------
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// (https://www.apache.org/licenses/LICENSE-2.0)

// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// CONSTANTS ------------------------------------------------------------------

const CATEGORIES = [
  "Mots de 3 lettres",
  "Mots de 4 lettres",
  "Mots de 9 lettres",
  "Un prénom de garçon",
  "Un prénom mixte",
  "Un prénom de fille",
  "Prénom dans votre famille",
  "Acronymes",
  "Adjectifs",
  "Jouets pour adultes",
  "Compagnies aériennes",
  "Bruits d'animaux",
  "Animaux",
  "Les animaux dans les livres ou les films",
  "Appareils électroménagers",
  "Vêtements",
  "Athlètes",
  "Auteurs",
  "Prix/cérémonies",
  "Aliments pour bébés",
  "Objets dans le jardin",
  "Mauvaises habitudes",
  "Oiseaux",
  "Jeux de société",
  "Étendues d'eau",
  "Titres des livres",
  "Nourriture pour le petit déjeuner",
  "Capitales",
  "Jeux de cartes",
  "Pièces détachées pour voitures",
  "Voitures",
  "Personnages de dessins animés",
  "Catégories dans ce jeu",
  "Célébrités",
  "Céréales",
  "Livres pour enfants",
  "Décorations de Noël",
  "Chants de Noël",
  "Marques de vêtements",
  "École/Collèges/Lycée/Universités",
  "Couleurs",
  "Entreprises",
  "Compositeurs",
  "Pièces d'ordinateur",
  "Programmes informatiques",
  "Ustensiles de cuisine",
  "Cosmétiques/accessoires de toilette",
  "Pays",
  "Monnaies",
  "Gros mots",
  "Produits laitiers",
  "Métiers",
  "Desserts",
  "Aliments diététiques",
  "Maladies",
  "Documents",
  "Gadgets électroniques",
  "Éléments du tableau périodique",
  "Emotions",
  "Excuses pour le retard",
  "Tissus",
  "Criminels célèbres",
  "Duos et trios célèbres",
  "Femmes célèbres",
  "Des gens célèbres qui ne sont pas blancs",
  "Citations célèbres",
  "Animaux de ferme",
  "Cadeaux/activités de la fête des pères",
  "Fétiches",
  "Personnages de fiction",
  "Poissons",
  "Fleurs",
  "Nourriture/boisson qui est verte",
  "Nourriture/boisson qui est rouge",
  "Nourriture/boisson qui est jaune",
  "Les aliments que vous cuisinez",
  "Les aliments que vous mangez crus",
  "Chaussures",
  "Villes étrangères",
  "Mots étrangers utilisés en français",
  "Fruits",
  "Meubles",
  "Jeux",
  "Gaz",
  "Cadeaux",
  "Dieux et divinités",
  "Termes de grammaire",
  "Coiffure",
  "Personnalités historiques",
  "Événements historiques",
  "Passions",
  "Activités de vacances",
  "Vacances",
  "Endroit pour partir en de lune de miel",
  "Hôtels",
  "Tâches ménagères",
  "Mots composés",
  "Saveurs de glaces",
  "Sports d'intérieur",
  "Infrastructure",
  "Blessures",
  "Insectes",
  "Jargon Internet",
  "Choses invisibles",
  "Objets dans un coffre de voiture",
  "Articles dans un catalogue",
  "Articles dans un panier cadeau",
  "Articles dans une boîte à gants",
  "Objets dans une cuisine",
  "Objets dans un casier",
  "Objets dans une table de nuit",
  "Articles dans un réfrigérateur",
  "Objets dans une valise",
  "Articles dans un distributeur automatique",
  "Objet dans cette pièce",
  "Objet dans votre sac à main/portefeuille",
  "Articles que vous voulez pour Noël",
  "Objets que vous emmenez en voyage",
  "Bijoux",
  "Malbouffe",
  "Types de sacs",
  "Sortes de bonbons",
  "Genres de danses",
  "Des sortes de soupe",
  "Langues",
  "Termes juridiques",
  "Activités de loisirs",
  "Personnes LGBTQ célèbres",
  "Boissons alcoolisées",
  "Magazines",
  "Emplois manuels",
  "Termes mathématiques",
  "Objets mécaniques",
  "Termes médicaux",
  "Médicaments/drogues",
  "Termes dans un menu",
  "Choses microscopiques",
  "Vedettes de cinéma",
  "Titres de films",
  "Groupes musicaux",
  "Instruments de musique",
  "Noms dans la Bible",
  "Les mots de la veille du Nouvel An",
  "Surnoms",
  "Personnes notoires",
  "Objets fabriqués avant 1900",
  "Choses obsolètes",
  "Professions",
  "Événements olympiques",
  "Peintres/sculpteurs",
  "Parcs",
  "Parties du corps",
  "Personnes en uniforme",
  "Traits de personnalité",
  "Animaux de compagnie",
  "Apps téléphoniques",
  "Garnitures pour pizza",
  "Lieux en Europe",
  "Lieux pour traîner",
  "Endroits où les gens font l'amour",
  "Lieux où l'on peut être nu",
  "Lieux où vous pouvez vous faire piéger",
  "Lieux où vous devez porter un chapeau",
  "Lieux où vous n'avez pas le droit d'aller",
  "Plantes",
  "Jouer des titres",
  "Activités privées",
  "Noms de produits",
  "Équipes sportives professionnelles",
  "Raisons d'appeler le 112",
  "Raisons d'appeler votre ex",
  "Raisons d'appeler votre mère",
  "Raisons de changement d'adresse",
  "Raisons de voler",
  "Raisons de faire appel à une baby-sitter",
  "Raisons de divorcer",
  "Raisons pour lesquelles il faut prendre un avocat",
  "Raisons d'obtenir un prêt",
  "Raisons de prendre un verre",
  "Raisons de passer un appel téléphonique",
  "Raisons de consulter un thérapeute",
  "Raisons de gifler quelqu'un",
  "Raisons de rester à la maison",
  "Raisons de rester debout toute la nuit",
  "Raisons de quitter votre emploi",
  "Raisons de tweeter",
  "Symboles religieux",
  "Reptiles/amphibiens",
  "Restaurants",
  "Pièces de la maison",
  "Sandwiches",
  "Matières scolaires",
  "Fournitures scolaires",
  "Termes de science-fiction",
  "Scientifiques célèbres",
  "Fruits de mer",
  "Panneaux de signalisation",
  "Insultes",
  "Logiciel",
  "Quelque chose dont vous avez peur",
  "Quelque chose que vous gardez caché",
  "Titres des chansons",
  "Sources de lumière ou de chaleur",
  "Épices et herbes",
  "Nourriture épicée",
  "Sports",
  "Équipements sportifs",
  "Pays",
  "Termes statistiques",
  "Pierres",
  "Noms de magasins",
  "Noms de rue",
  "Noms de famille",
  "Symptômes",
  "Activités d'équipe",
  "Entreprises technologiques",
  "Termes d'affection",
  "Termes de mesure",
  "Termes de théâtre",
  "Choses à faire dans un cirque",
  "Choses sur un chantier de construction",
  "Choses à faire lors d'un match de football",
  "Choses à faire lors d'un enterrement",
  "Choses à faire dans un gymnase",
  "Choses dans un musée",
  "Choses à un défilé",
  "Choses à faire lors d'un mariage",
  "Choses au Mont Everest",
  "Choses à la plage",
  "Objets trouvés dans un bar",
  "Objets trouvés sur un canapé",
  "Objets trouvés dans un bureau",
  "Objets trouvés dans un hôpital",
  "Objets trouvés à Abu Dhabi",
  "Objets trouvés au Caire",
  "Objets trouvés à Paris",
  "Objets trouvés à Rio",
  "Choses trouvées dans l'océan",
  "Objets trouvés à Tokyo",
  "Objets trouvés sur une carte",
  "Choses trouvées sur les réseaux sociaux",
  "Choses dans un sac à dos",
  "Choses dans une baignoire/douche",
  "Choses dans une grotte",
  "Choses dans une salle d'audience",
  "Choses dans une épicerie",
  "Choses dans un centre commercial",
  "Choses dans une armoire à pharmacie",
  "Choses en Antarctique",
  "Choses dans un parc",
  "Choses dans un magasin de souvenirs",
  "Choses dans l'espace",
  "Choses dans le désert",
  "Choses dans le ciel",
  "Choses faites de tissu",
  "Choses en verre",
  "Choses en métal",
  "Choses en bois",
  "Choses sur un bateau de croisière",
  "Choses sur une île déserte",
  "Choses sur un terrain de golf",
  "Choses sur un toit",
  "Choses sur un mur",
  "Choses que seuls les riches possèdent",
  "Choses sur la lune",
  "Choses au fond de l'océan",
  "Choses vendues derrière le comptoir",
  "Choses qui s'apprécient",
  "Choses qui sont noires",
  "Choses qui sont bleues",
  "Choses qui sont froides",
  "Choses qui sont plates",
  "Choses qui sont poilues/duveteuses",
  "Choses qui sont chaudes",
  "Choses qui sont illégales",
  "Choses qui sont rouges",
  "Choses qui sont rondes",
  "Choses qui sont carrées",
  "Choses qui sont molles",
  "Choses qui sont collantes",
  "Choses qui sont triangulaires",
  "Choses qui sont blanches",
  "Choses qui peuvent vous tuer",
  "Choses qui coûtent environ 10 euros",
  "Choses qui coûtent environ 100 euros",
  "Choses qui coûtent environ 1000 euros",
  "Choses qui se déprécient",
  "Choses qui vous font virer",
  "Choses qui montent et descendent",
  "Choses qui grandissent",
  "Choses qui ont des boutons",
  "Choses qui ont des taches",
  "Choses qui ont des rayures",
  "Choses qui ont des roues",
  "Choses qui sautent / rebondissent",
  "Choses qui vous font sourire",
  "Choses qui ne bougent jamais",
  "Choses qui ne devraient pas être mouillées",
  "Choses qui tournent",
  "Choses qui ont une télécommande",
  "Choses uniques au monde",
  "Choses à faire lors d'une fête",
  "Choses à faire lors d'un rendez-vous",
  "Choses avec des trous",
  "Choses avec des queues",
  "Choses auxquelles vous êtes allergique",
  "Choses qui brûlent",
  "Choses que vous achetez pour les enfants",
  "Choses que vous pouvez mettre en gage",
  "Choses qu'on attrape",
  "Choses auquelles on peut grimper",
  "Choses que vous faites au travail",
  "Choses que vous faites tous les jours",
  "Choses que vous pouver acheter sur Amazon",
  "Choses que vous recevez par courrier",
  "Choses pour lesquelles vous obtenez des billets",
  "Choses que vous cachez aux parents",
  "Choses dans lesquelles vous investissez",
  "Choses que l'on garde pour toujours",
  "Choses que vous faites",
  "Choses qu'on ne fait qu'une fois",
  "Choses qu'on ouvre",
  "Choses que vous branchez",
  "Choses que vous tirez",
  "Choses que vous recyclez",
  "Choses que vous remplacez",
  "Choses qu'on frotte à soi-même",
  "Choses qu'on voit au zoo",
  "Choses que l'on voit avec un télescope",
  "Choses qu'il ne faut pas toucher",
  "Choses qui vous fait crier",
  "Objets dans lesquels vous stockez des objets",
  "Choses que l'on jette",
  "Choses que vous portez",
  "Choses qu'on murmure",
  "Ce que vous écrivez dans une carte",
  "Titres que les gens peuvent avoir",
  "Outils",
  "Sujets d'actualité",
  "Attractions touristiques",
  "Jouets",
  "Arbres",
  "Lieux tropicaux",
  "Émissions de télévision",
  "Vedettes de la télé",
  "Types de boissons",
  "Météo",
  "Choses incassables",
  "Choses souterraines",
  "Liquides non potables",
  "Spots de vacances",
  "Mots de la Saint-Valentin",
  "Légumes",
  "Véhicules",
  "Jeux vidéo",
  "Méchants/monstres",
  "Termes de guerre",
  "Les moyens de communiquer",
  "Façons de flirter",
  "Les moyens d'aller d'ici à là",
  "Les moyens de devenir riche",
  "Des moyens de tuer le temps",
  "Façons de dire bonjour/au revoir",
  "Les moyens de dire oui ou non",
  "Les moyens de dire que vous êtes désolé",
  "Façons de passer sa retraite",
  "Façons de dire l'heure/la date",
  "Armes",
  "Sites web",
  "Activités du week-end",
  "Animaux sauvages",
  "Lieux d'hiver",
  "Choses sans fil",
  "Mots liés à l'art",
  "Mots relatifs à votre poids",
  "Mots liés au café/thé",
  "Mots liés à l'exercice",
  "Mots relatifs à la maternelle",
  "Mots liés à l'argent",
  "Mots liés au sexe",
  "Mots se terminant par un 'E'",
  "Mots se terminant par un 'L'",
  "Mots se terminant par un 'N'",
  "Mots se terminant par un 'R'",
  "Mots se terminant par un 'T'",
  "Mots avec des lettres doubles",
  "Mots avec exactement 2 voyelles",
  "Mots avec exactement 3 voyelles",
  "Des mots aux significations multiples",
  "Leaders mondiaux/politiciens",
  "Fromages"
];

const LOCAL_CATEGORIES = {
  /*'Jamaica': [
    "Caribbean foods",
    "Jamaican personalities",
    "Jamaican towns/cities",
    "Things at a cricket game",
    "Things at Jamaica Carnival",
    "Things found in Kingston",
    "Words from Jamaican patois"
  ],
  'UK': [
    "British towns/cities",
    "Things found in London"
  ],
  'US': [
    "American cities",
    "American foods",
    "Thanksgiving items",
    "Things at a baseball game",
    "Things at a basketball game",
    "Things at the Superbowl",
    "Things found in New York",
    "Things in the Oval Office",
  ]*/
}
